### ISSUE TITLE
False positives for spam detection

### ISSUE THREAD

**Issue by ParaLogia** [benjamingorman/KAGLadder#32]
The spam detector will occasionally filter out a chat message for spam when the user is not, in fact, spamming. This is a scenario where it occurs:

1. Round begins (game time = 0)
2. Player chats (game time = X)
3. Round ends, new round begins (game time = 0, again)
4. Player chats (game time = X-10)
5. Message gets suppressed

In other words the condition (getGameTime() > lastChatTime) in SpamPrevention.as does not ensure that previous rounds don't affect future rounds. 

I'm not familiar enough with KAG code to suggest an exact fix, but you might have to clear the SPAM_PREVENTION dictionary every time the round switches.

**Comment by benjamingorman** [comment]
Thanks for the good bug report.
Although I decided just to remove the spam prevention - it's more likely to cause issues that fix them.
